// <auto-generated />
namespace BankOfBIT_JG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Milestone4Models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Milestone4Models));
        
        string IMigrationMetadata.Id
        {
            get { return "202002010130228_Milestone4Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
